[package]
name = "transfer"
version = "0.1.0"
authors = ["Yu Haidong"]
edition = "2018"

[dependencies]
futures = { version = "0.3.30" }
log = "0.4.21"
tokio = { version = "1.36.0", features = ["full"] }
tokio-tungstenite = "0.21.0"
