[package]
name = "transfer"
version = "0.1.0"
authors = ["Yu Haidong"]
edition = "2018"

[dependencies]
futures = { workspace = true }
log = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
